<?php

function researchit_user_menu() {
  $items['user-test'] = array(
    'title' => 'User Test',
    'page callback' => 'researchit_user_user_login',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'management',
    );
  $items['projects'] = array(
    'title' => 'Projects',
    'page callback' => 'researchit_user_projects',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
    );
  return $items;
}

function rest_request($endpoint, $method = 'GET', $postdata = '') {
  $opts = array(
    'http'=>array(
      'method'=> $method,
      'ignore_errors' => true,
      'content' => $postdata,
      'timeout' => 15,
      'header'=>"Accept: application/json\r\n" .
                "Content-Type: application/json\r\n" .
                "Authorization:Basic " . base64_encode(
                "researchit:Fj27RP0741HS0N2") . "\r\n" .
                "User-Agent: drupal\r\n"
    )
  );
  $context = stream_context_create($opts);
  $json = file_get_contents("https://projects.nesi.org.nz/projectdb/rest/$endpoint", false, $context);
  $data = json_decode($json);
  return $data;
}

function researchit_user_user_login() {
  global $user;
  if (empty($_SERVER['auEduPersonSharedToken']) || empty($_SERVER['uid'])) return;
  $token = $_SERVER['auEduPersonSharedToken'];
  if ($token == 'kGD3LK4S0r323WRQuiA_gKJi8zw' || $token == 'rgkEhlRdAommwY311bAyAJcaOEQ') $token = 'VMu6uT-7WucYcdNE8ZjvkQ1TXl0'; // Nick/Richard = John Cater
  
  $researcher = rest_request('researchers/tuakiri', 'POST', $token);
  if (!isset($researcher->message)) {
    $id = $researcher->id;
    $researcher->projects = rest_request("researchers/$id/projects");
    usort($researcher->projects, function($a, $b) {
      if ($a->statusId == $b->statusId) {
        return $a->startDate < $b->startDate;
      } else {
        return $a->statusId > $b->statusId;
      }
    });
  }
  
  $cn = escapeshellarg($_SERVER['uid']);
  $ldapInfo = `ldapsearch -H ldaps://uoa.auckland.ac.nz -D svc-uoaldap -w '$0m(4U!3i3C8' -b 'dc=uoa,dc=auckland,dc=ac,dc=nz' '(cn=$cn)'`;
  $ldapInfo = str_replace("\n ", "", $ldapInfo);
  $ldapInfo = explode("\n", $ldapInfo);
  $ldapGroups = array();
  $ldapAttributes = array();
  
  foreach ($ldapInfo as $line) {
    if (strpos($line, 'memberOf: CN=') === 0) {
      $matches = array();
      preg_match('/^memberOf: CN=(.+?),/', $line, $matches);
      $ldapGroups[] = $matches[1];
    } else if (!empty($line) && $line[0] != '#') {
      $bits = explode(': ', $line, 2);
      $name = trim($bits[0], ':');
      $ldapAttributes[$name] = $bits[1];
    }
  }
  
  user_save($user, array('data' => array('projectdb_info' => $researcher, 'ldap_groups' => $ldapGroups, 'ldap_attributes' => $ldapAttributes)));
  dpm($_SERVER);
  dpm($user);
  print theme('status_messages');
}

function researchit_user_node_access($node, $op, $account) {
  if (!empty($node->field_edit_groups['und'][0]['value'])) {
    $allowedGroups = explode(',', $node->field_edit_groups['und'][0]['value']);
    if ($op == 'update' && array_intersect($account->data['ldap_groups'], $allowedGroups)) {
      return NODE_ACCESS_ALLOW;
    }
  }
}

function researchit_user_theme($existing, $type, $theme, $path) {
  $variables = array();
  return array(
    'researchit_user_project' => array(
      'variables' => $variables,
      'template' => 'researchit-user-project',
      'path' => drupal_get_path('module', 'researchit_user') .'/templates'
    )
  );
}

function researchit_user_projects($projectCode = '') {
  global $user;
  if (empty($user->data['projectdb_info'])) {
    drupal_goto('Shibboleth.sso/Login');
    return '';
  }
  $found = false;
  foreach ($user->data['projectdb_info']->projects as $p) {
    if ($p->projectCode == $projectCode) {
      $found = true;
      break;
    }
  }
  if (!$found) {
    drupal_set_message("Error: you don't seem to be listed on the project $projectCode");
    return "";
  }
  $project_wrapper = rest_request("projects/" . $projectCode);
  $project_wrapper->properties = rest_request("projects/{$project_wrapper->project->id}/prop");
  drupal_set_title($project_wrapper->project->name);
  $variables = array(
    'pw' => $project_wrapper,
  );
  dpm($variables);
  return theme('researchit_user_project', $variables);
}